// flow-typed signature: 3a9c09c8c25a6fc122c5a77295c0b62f
// flow-typed version: <<STUB>>/inject-env_v^0.7.3/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inject-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'inject-env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'inject-env/index' {
  declare module.exports: $Exports<'inject-env'>;
}
declare module 'inject-env/index.js' {
  declare module.exports: $Exports<'inject-env'>;
}
