// flow-typed signature: 065667cda2c28f76aedffe033469eef0
// flow-typed version: <<STUB>>/json-injector_v^0.4.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json-injector'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json-injector' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'json-injector/lib/app' {
  declare module.exports: any;
}

declare module 'json-injector/lib/injectors/env-var' {
  declare module.exports: any;
}

declare module 'json-injector/lib/injectors/file' {
  declare module.exports: any;
}

declare module 'json-injector/lib/schema/index' {
  declare module.exports: any;
}

declare module 'json-injector/lib/schema/injectors/env-var-options' {
  declare module.exports: any;
}

declare module 'json-injector/lib/schema/injectors/file-options' {
  declare module.exports: any;
}

declare module 'json-injector/lib/schema/injectors/index' {
  declare module.exports: any;
}

declare module 'json-injector/lib/schema/options' {
  declare module.exports: any;
}

declare module 'json-injector/lib/schema/schema' {
  declare module.exports: any;
}

// Filename aliases
declare module 'json-injector/lib/app.js' {
  declare module.exports: $Exports<'json-injector/lib/app'>;
}
declare module 'json-injector/lib/injectors/env-var.js' {
  declare module.exports: $Exports<'json-injector/lib/injectors/env-var'>;
}
declare module 'json-injector/lib/injectors/file.js' {
  declare module.exports: $Exports<'json-injector/lib/injectors/file'>;
}
declare module 'json-injector/lib/schema/index.js' {
  declare module.exports: $Exports<'json-injector/lib/schema/index'>;
}
declare module 'json-injector/lib/schema/injectors/env-var-options.js' {
  declare module.exports: $Exports<'json-injector/lib/schema/injectors/env-var-options'>;
}
declare module 'json-injector/lib/schema/injectors/file-options.js' {
  declare module.exports: $Exports<'json-injector/lib/schema/injectors/file-options'>;
}
declare module 'json-injector/lib/schema/injectors/index.js' {
  declare module.exports: $Exports<'json-injector/lib/schema/injectors/index'>;
}
declare module 'json-injector/lib/schema/options.js' {
  declare module.exports: $Exports<'json-injector/lib/schema/options'>;
}
declare module 'json-injector/lib/schema/schema.js' {
  declare module.exports: $Exports<'json-injector/lib/schema/schema'>;
}
