// flow-typed signature: d7d4c5ca78d1cc4834070e177675e3c2
// flow-typed version: <<STUB>>/react-native-version-check-expo_v^2.0.0-alpha.10/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-version-check-expo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-version-check-expo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-version-check-expo/src/ExpoVersionInfo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-version-check-expo/index' {
  declare module.exports: $Exports<'react-native-version-check-expo'>;
}
declare module 'react-native-version-check-expo/index.js' {
  declare module.exports: $Exports<'react-native-version-check-expo'>;
}
declare module 'react-native-version-check-expo/src/ExpoVersionInfo.js' {
  declare module.exports: $Exports<'react-native-version-check-expo/src/ExpoVersionInfo'>;
}
