// flow-typed signature: 98561bfb1e9532fda947fac821f6cefa
// flow-typed version: <<STUB>>/redux-saga-firebase_v^0.6.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-saga-firebase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-saga-firebase' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-saga-firebase/dist/auth' {
  declare module.exports: any;
}

declare module 'redux-saga-firebase/dist/database' {
  declare module.exports: any;
}

declare module 'redux-saga-firebase/dist/functions' {
  declare module.exports: any;
}

declare module 'redux-saga-firebase/dist/index' {
  declare module.exports: any;
}

declare module 'redux-saga-firebase/dist/messaging' {
  declare module.exports: any;
}

declare module 'redux-saga-firebase/dist/storage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-saga-firebase/dist/auth.js' {
  declare module.exports: $Exports<'redux-saga-firebase/dist/auth'>;
}
declare module 'redux-saga-firebase/dist/database.js' {
  declare module.exports: $Exports<'redux-saga-firebase/dist/database'>;
}
declare module 'redux-saga-firebase/dist/functions.js' {
  declare module.exports: $Exports<'redux-saga-firebase/dist/functions'>;
}
declare module 'redux-saga-firebase/dist/index.js' {
  declare module.exports: $Exports<'redux-saga-firebase/dist/index'>;
}
declare module 'redux-saga-firebase/dist/messaging.js' {
  declare module.exports: $Exports<'redux-saga-firebase/dist/messaging'>;
}
declare module 'redux-saga-firebase/dist/storage.js' {
  declare module.exports: $Exports<'redux-saga-firebase/dist/storage'>;
}
