// flow-typed signature: 344870f554f56a77e5cdd960f22b5e91
// flow-typed version: <<STUB>>/sentry-expo_v^1.6.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sentry-expo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sentry-expo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sentry-expo/upload-sourcemaps' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sentry-expo/index' {
  declare module.exports: $Exports<'sentry-expo'>;
}
declare module 'sentry-expo/index.js' {
  declare module.exports: $Exports<'sentry-expo'>;
}
declare module 'sentry-expo/upload-sourcemaps.js' {
  declare module.exports: $Exports<'sentry-expo/upload-sourcemaps'>;
}
