const INIT_APP = 'INIT_APP';

const SET_USER = 'SET_USER';

const SET_USER_DATA = 'SET_USER_DATA';

const CLEAR_USER_DATA = 'CLEAR_USER_DATA';

const SET_CACHE = 'SET_CACHE';

export { INIT_APP, SET_CACHE, SET_USER, SET_USER_DATA, CLEAR_USER_DATA };
