const INIT_APP = 'INIT_APP';

const SET_USER = 'SET_USER';

const SET_USER_DATA = 'SET_USER_DATA';

const CLEAR_USER_DATA = 'CLEAR_USER_DATA';

const ADD_FAVORITE = 'ADD_FAVORITE';

const REMOVE_FAVORITE = 'REMOVE_FAVORITE';

const ADD_SUGGESTION = 'ADD_SUGGESTION';
const REMOVE_SUGGESTION = 'REMOVE_SUGGESTION';

const FIREBASE_SUCCESS = 'FIREBASE_SUCCESS';

const FIREBASE_FAIL = 'FIREBASE_FAIL';

const SET_CACHE = 'SET_CACHE';

const LOGIN = 'LOGIN';

const LOGOUT = 'LOGOUT';

export {
  INIT_APP,
  SET_CACHE,
  SET_USER,
  SET_USER_DATA,
  CLEAR_USER_DATA,
  ADD_FAVORITE,
  REMOVE_FAVORITE,
  ADD_SUGGESTION,
  REMOVE_SUGGESTION,
  FIREBASE_SUCCESS,
  FIREBASE_FAIL,
  LOGIN,
  LOGOUT,
};
